#include "GridMap.h"

#include <algorithm>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <limits>
#include <queue>
#include <sstream>
#include <stdexcept>

namespace pathlab {

namespace {
constexpr int kMinSize = 5;
constexpr int kMaxRows = 120;
constexpr int kMaxCols = 180;

int ClampHeight(int value) {
    return std::clamp(value, 0, 9);
}

int ToInt(CellType type) {
    return type == CellType::Obstacle ? 1 : 0;
}

int ToInt(TerrainType terrain) {
    switch (terrain) {
        case TerrainType::Road: return 1;
        case TerrainType::Forest: return 2;
        case TerrainType::Water: return 3;
        case TerrainType::Mountain: return 4;
        case TerrainType::Plain:
        default: return 0;
    }
}

TerrainType TerrainFromInt(int value) {
    switch (value) {
        case 1: return TerrainType::Road;
        case 2: return TerrainType::Forest;
        case 3: return TerrainType::Water;
        case 4: return TerrainType::Mountain;
        case 0:
        default: return TerrainType::Plain;
    }
}
} // namespace

GridMap::GridMap(int rows, int cols) {
    Resize(rows, cols);
}

void GridMap::Resize(int rows, int cols) {
    rows_ = std::clamp(rows, kMinSize, kMaxRows);
    cols_ = std::clamp(cols, kMinSize, kMaxCols);
    cells_.assign(static_cast<size_t>(rows_ * cols_), Cell{});
    start_ = Index(rows_ / 2, cols_ / 5);
    goal_ = Index(rows_ / 2, cols_ * 4 / 5);
    EnsureEndpointsWalkable();
}

void GridMap::ClearAll() {
    std::fill(cells_.begin(), cells_.end(), Cell{});
    start_ = Index(rows_ / 2, cols_ / 5);
    goal_ = Index(rows_ / 2, cols_ * 4 / 5);
    EnsureEndpointsWalkable();
}

void GridMap::ClearObstacles() {
    for (auto& cell : cells_) {
        cell.type = CellType::Empty;
        if (cell.terrain == TerrainType::Water) {
            cell.terrain = TerrainType::Plain;
        }
    }
    EnsureEndpointsWalkable();
}

void GridMap::ResetTerrain() {
    for (auto& cell : cells_) {
        cell.terrain = TerrainType::Plain;
        cell.height = 0;
    }
    EnsureEndpointsWalkable();
}

void GridMap::GenerateRandom(float obstacleProbability, unsigned seed) {
    obstacleProbability = std::clamp(obstacleProbability, 0.0f, 0.75f);
    std::mt19937 rng(seed);
    std::bernoulli_distribution obstacleDist(obstacleProbability);
    std::uniform_int_distribution<int> terrainDist(0, 99);
    std::uniform_int_distribution<int> heightDist(0, 9);

    for (auto& cell : cells_) {
        cell = Cell{};
        int terrainRoll = terrainDist(rng);
        if (terrainRoll < 10) cell.terrain = TerrainType::Road;
        else if (terrainRoll < 24) cell.terrain = TerrainType::Forest;
        else if (terrainRoll < 31) cell.terrain = TerrainType::Mountain;
        else cell.terrain = TerrainType::Plain;

        cell.height = heightDist(rng);
        cell.type = obstacleDist(rng) ? CellType::Obstacle : CellType::Empty;
    }

    start_ = PickRandomFreeCell(rng);
    goal_ = PickRandomFreeCell(rng);

    for (int attempt = 0; attempt < 500; ++attempt) {
        int candidate = PickRandomFreeCell(rng);
        GridCoord s = Coord(start_);
        GridCoord g = Coord(candidate);
        int manhattan = std::abs(s.row - g.row) + std::abs(s.col - g.col);
        if (manhattan > (rows_ + cols_) / 3) {
            goal_ = candidate;
            break;
        }
    }
    EnsureEndpointsWalkable();
}

void GridMap::GenerateTerrain(unsigned seed) {
    // Continuous-looking landscape generator. Internally it is still a grid,
    // but elevation and terrain patches are generated by smooth analytic fields.
    std::mt19937 rng(seed);
    std::uniform_real_distribution<double> unit(0.0, 1.0);

    struct Hill {
        double x = 0.0;
        double y = 0.0;
        double radius = 0.25;
        double amplitude = 1.0;
    };

    std::vector<Hill> hills;
    for (int i = 0; i < 9; ++i) {
        Hill h;
        h.x = unit(rng);
        h.y = unit(rng);
        h.radius = 0.12 + unit(rng) * 0.28;
        h.amplitude = (unit(rng) < 0.30 ? -1.0 : 1.0) * (0.65 + unit(rng) * 1.35);
        hills.push_back(h);
    }

    std::vector<double> raw(static_cast<size_t>(Count()), 0.0);
    double minValue = std::numeric_limits<double>::infinity();
    double maxValue = -std::numeric_limits<double>::infinity();

    auto normX = [&](int col) -> double {
        return cols_ <= 1 ? 0.0 : static_cast<double>(col) / static_cast<double>(cols_ - 1);
    };
    auto normY = [&](int row) -> double {
        return rows_ <= 1 ? 0.0 : static_cast<double>(row) / static_cast<double>(rows_ - 1);
    };

    for (int r = 0; r < rows_; ++r) {
        for (int c = 0; c < cols_; ++c) {
            const double x = normX(c);
            const double y = normY(r);
            double value = 0.24 * std::sin(7.5 * x + 2.2 * std::sin(3.1 * y))
                         + 0.18 * std::cos(6.5 * y + 1.7 * std::sin(4.0 * x));
            for (const Hill& h : hills) {
                const double dx = x - h.x;
                const double dy = y - h.y;
                const double d2 = dx * dx + dy * dy;
                value += h.amplitude * std::exp(-d2 / (2.0 * h.radius * h.radius));
            }
            raw[static_cast<size_t>(Index(r, c))] = value;
            minValue = std::min(minValue, value);
            maxValue = std::max(maxValue, value);
        }
    }

    const double range = std::max(1.0e-9, maxValue - minValue);

    // Meandering road and river. They are not “height”; they are semantic terrain layers.
    const double roadPhase = unit(rng) * 6.28318530718;
    const double riverPhase = unit(rng) * 6.28318530718;

    std::vector<GridCoord> roadCells;
    std::vector<GridCoord> riverCells;

    for (auto& cell : cells_) {
        cell = Cell{};
    }

    for (int r = 0; r < rows_; ++r) {
        for (int c = 0; c < cols_; ++c) {
            const int idx = Index(r, c);
            Cell& cell = cells_[static_cast<size_t>(idx)];
            const double normalized = (raw[static_cast<size_t>(idx)] - minValue) / range;
            cell.height = ClampHeight(static_cast<int>(std::round(normalized * 9.0)));
            cell.type = CellType::Empty;
            cell.terrain = TerrainType::Plain;

            const double x = normX(c);
            const double y = normY(r);
            const double roadY = 0.50 + 0.12 * std::sin(6.0 * x + roadPhase) + 0.04 * std::sin(17.0 * x);
            const double riverY = 0.27 + 0.16 * std::sin(5.0 * x + riverPhase) + 0.05 * std::sin(13.0 * x + 1.5);

            const double roadDist = std::abs(y - roadY);
            const double riverDist = std::abs(y - riverY);

            if (riverDist < 0.020 || normalized < 0.075) {
                cell.terrain = TerrainType::Water;
                cell.type = CellType::Obstacle;
                riverCells.push_back({ r, c });
            }
            if (normalized > 0.70) {
                cell.terrain = TerrainType::Mountain;
            }
            if (normalized > 0.33 && normalized < 0.66) {
                // Forest blobs are smooth but not tied to height.
                const double forestSignal = std::sin(11.0 * x + 4.0 * std::sin(5.0 * y))
                                          + std::cos(9.0 * y + 2.5 * std::sin(6.0 * x));
                if (forestSignal > 0.72) cell.terrain = TerrainType::Forest;
            }
            if (roadDist < 0.025) {
                // Roads override most terrain and remain walkable. This creates realistic detours.
                cell.terrain = TerrainType::Road;
                cell.type = CellType::Empty;
                roadCells.push_back({ r, c });
                // Slightly cut the road into the terrain so it looks like infrastructure,
                // not a mountain category.
                if (cell.height > 0) cell.height = std::max(0, cell.height - 1);
            }
        }
    }

    // Add a few bridges where road crosses river so car/pedestrian paths can actually choose crossings.
    for (const GridCoord& road : roadCells) {
        for (int dr = -1; dr <= 1; ++dr) {
            for (int dc = -1; dc <= 1; ++dc) {
                const int rr = road.row + dr;
                const int cc = road.col + dc;
                if (!InBounds(rr, cc)) continue;
                Cell& cell = cells_[static_cast<size_t>(Index(rr, cc))];
                if (cell.terrain == TerrainType::Water) {
                    cell.terrain = TerrainType::Road;
                    cell.type = CellType::Empty;
                }
            }
        }
    }

    // Pick endpoints near the road, far apart, to make the effect of terrain semantics visible.
    int startRow = rows_ / 2;
    int startCol = std::max(1, cols_ / 12);
    int goalRow = rows_ / 2;
    int goalCol = std::min(cols_ - 2, cols_ * 11 / 12);
    if (!roadCells.empty()) {
        auto nearestRoad = [&](int targetCol) {
            GridCoord best = roadCells.front();
            int bestScore = 1000000000;
            for (const GridCoord& rc : roadCells) {
                int score = std::abs(rc.col - targetCol) * 3 + std::abs(rc.row - rows_ / 2);
                if (score < bestScore) {
                    bestScore = score;
                    best = rc;
                }
            }
            return best;
        };
        GridCoord s = nearestRoad(startCol);
        GridCoord g = nearestRoad(goalCol);
        startRow = s.row;
        startCol = s.col;
        goalRow = g.row;
        goalCol = g.col;
    }
    start_ = Index(startRow, startCol);
    goal_ = Index(goalRow, goalCol);
    EnsureEndpointsWalkable();
}

void GridMap::GenerateMaze(unsigned seed) {
    // A compact recursive-backtracking maze generator on an odd-cell lattice.
    // Cells on even coordinates become walls; odd coordinates are carved as paths.
    std::mt19937 rng(seed);
    for (auto& cell : cells_) {
        cell = Cell{};
        cell.type = CellType::Obstacle;
    }

    auto carve = [&](int row, int col) {
        if (InBounds(row, col)) {
            int idx = Index(row, col);
            cells_[static_cast<size_t>(idx)].type = CellType::Empty;
            cells_[static_cast<size_t>(idx)].terrain = TerrainType::Plain;
            cells_[static_cast<size_t>(idx)].height = 0;
        }
    };

    int startRow = 1;
    int startCol = 1;
    carve(startRow, startCol);

    std::vector<GridCoord> stack;
    stack.push_back({ startRow, startCol });

    while (!stack.empty()) {
        GridCoord current = stack.back();
        std::vector<GridCoord> candidates;
        const int dr[4] = { -2, 2, 0, 0 };
        const int dc[4] = { 0, 0, -2, 2 };
        for (int k = 0; k < 4; ++k) {
            int nr = current.row + dr[k];
            int nc = current.col + dc[k];
            if (InBounds(nr, nc) && IsObstacle(Index(nr, nc))) {
                candidates.push_back({ nr, nc });
            }
        }
        if (candidates.empty()) {
            stack.pop_back();
            continue;
        }
        std::uniform_int_distribution<int> pick(0, static_cast<int>(candidates.size()) - 1);
        GridCoord next = candidates[static_cast<size_t>(pick(rng))];
        carve((current.row + next.row) / 2, (current.col + next.col) / 2);
        carve(next.row, next.col);
        stack.push_back(next);
    }

    start_ = Index(1, 1);
    int goalRow = (rows_ % 2 == 0) ? rows_ - 3 : rows_ - 2;
    int goalCol = (cols_ % 2 == 0) ? cols_ - 3 : cols_ - 2;
    goalRow = std::max(1, goalRow);
    goalCol = std::max(1, goalCol);
    goal_ = Index(goalRow, goalCol);
    EnsureEndpointsWalkable();
}

bool GridMap::SaveToFile(const std::string& path) const {
    try {
        std::filesystem::path filePath(path);
        if (filePath.has_parent_path()) {
            std::filesystem::create_directories(filePath.parent_path());
        }
        std::ofstream out(path);
        if (!out) return false;
        out << "PATHLAB_MAP_V1\n";
        out << rows_ << ' ' << cols_ << '\n';
        out << start_ << ' ' << goal_ << '\n';
        for (const auto& cell : cells_) {
            out << ToInt(cell.type) << ' ' << ToInt(cell.terrain) << ' ' << cell.height << '\n';
        }
        return true;
    } catch (...) {
        return false;
    }
}

bool GridMap::LoadFromFile(const std::string& path, std::string* errorMessage) {
    std::ifstream in(path);
    if (!in) {
        if (errorMessage != nullptr) *errorMessage = "Cannot open file: " + path;
        return false;
    }

    std::string magic;
    std::getline(in, magic);
    if (magic != "PATHLAB_MAP_V1") {
        if (errorMessage != nullptr) *errorMessage = "Unsupported map file format.";
        return false;
    }

    int rows = 0;
    int cols = 0;
    int start = 0;
    int goal = 0;
    if (!(in >> rows >> cols >> start >> goal)) {
        if (errorMessage != nullptr) *errorMessage = "Corrupted map header.";
        return false;
    }

    rows = std::clamp(rows, kMinSize, kMaxRows);
    cols = std::clamp(cols, kMinSize, kMaxCols);
    std::vector<Cell> loaded(static_cast<size_t>(rows * cols));

    for (int i = 0; i < rows * cols; ++i) {
        int type = 0;
        int terrain = 0;
        int height = 0;
        if (!(in >> type >> terrain >> height)) {
            if (errorMessage != nullptr) *errorMessage = "Corrupted cell data.";
            return false;
        }
        loaded[static_cast<size_t>(i)].type = type == 1 ? CellType::Obstacle : CellType::Empty;
        loaded[static_cast<size_t>(i)].terrain = TerrainFromInt(terrain);
        loaded[static_cast<size_t>(i)].height = ClampHeight(height);
    }

    rows_ = rows;
    cols_ = cols;
    cells_ = std::move(loaded);
    start_ = std::clamp(start, 0, Count() - 1);
    goal_ = std::clamp(goal, 0, Count() - 1);
    EnsureEndpointsWalkable();
    return true;
}

bool GridMap::InBounds(int row, int col) const {
    return row >= 0 && row < rows_ && col >= 0 && col < cols_;
}

const Cell& GridMap::GetCell(int index) const {
    if (index < 0 || index >= Count()) throw std::out_of_range("Cell index out of range");
    return cells_[static_cast<size_t>(index)];
}

Cell& GridMap::GetCell(int index) {
    if (index < 0 || index >= Count()) throw std::out_of_range("Cell index out of range");
    return cells_[static_cast<size_t>(index)];
}

bool GridMap::IsObstacle(int index) const {
    if (index < 0 || index >= Count()) return true;
    return cells_[static_cast<size_t>(index)].type == CellType::Obstacle;
}

bool GridMap::IsWater(int index) const {
    if (index < 0 || index >= Count()) return false;
    return cells_[static_cast<size_t>(index)].terrain == TerrainType::Water;
}

bool GridMap::IsWalkable(int index) const {
    return IsWalkable(index, MovementProfile::Pedestrian);
}

bool GridMap::IsWalkable(int index, MovementProfile profile) const {
    if (index < 0 || index >= Count()) return false;
    if (profile == MovementProfile::Drone) {
        // Drone is a planning profile that flies over terrain layers and obstacles.
        // This makes the same map produce a very different path and demonstrates
        // how changing the cost model changes the meaning of “shortest”.
        return true;
    }
    return !IsObstacle(index) && !IsWater(index);
}

void GridMap::SetObstacle(int index, bool obstacle) {
    if (index < 0 || index >= Count()) return;
    if (index == start_ || index == goal_) return;
    cells_[static_cast<size_t>(index)].type = obstacle ? CellType::Obstacle : CellType::Empty;
    if (!obstacle && cells_[static_cast<size_t>(index)].terrain == TerrainType::Water) {
        cells_[static_cast<size_t>(index)].terrain = TerrainType::Plain;
    }
}

void GridMap::SetTerrain(int index, TerrainType terrain) {
    if (index < 0 || index >= Count()) return;
    cells_[static_cast<size_t>(index)].terrain = terrain;
    if (terrain == TerrainType::Water) cells_[static_cast<size_t>(index)].type = CellType::Obstacle;
    if (index == start_ || index == goal_) EnsureEndpointsWalkable();
}

void GridMap::SetHeight(int index, int height) {
    if (index < 0 || index >= Count()) return;
    cells_[static_cast<size_t>(index)].height = ClampHeight(height);
}

void GridMap::AddHeight(int index, int delta) {
    if (index < 0 || index >= Count()) return;
    cells_[static_cast<size_t>(index)].height = ClampHeight(cells_[static_cast<size_t>(index)].height + delta);
}

void GridMap::SetStart(int index) {
    if (!IsWalkable(index) || index == goal_) return;
    start_ = index;
}

void GridMap::SetGoal(int index) {
    if (!IsWalkable(index) || index == start_) return;
    goal_ = index;
}

std::vector<int> GridMap::Neighbors(int index, bool allowDiagonal) const {
    return Neighbors(index, allowDiagonal, MovementProfile::Pedestrian);
}

std::vector<int> GridMap::Neighbors(int index, bool allowDiagonal, MovementProfile profile) const {
    std::vector<int> result;
    GridCoord c = Coord(index);
    const int dr8[8] = { -1, 1, 0, 0, -1, -1, 1, 1 };
    const int dc8[8] = { 0, 0, -1, 1, -1, 1, -1, 1 };
    int count = allowDiagonal ? 8 : 4;

    for (int k = 0; k < count; ++k) {
        int nr = c.row + dr8[k];
        int nc = c.col + dc8[k];
        if (InBounds(nr, nc)) {
            int next = Index(nr, nc);
            if (!IsWalkable(next, profile)) continue;

            if (k >= 4 && profile != MovementProfile::Drone) {
                // Avoid cutting through two diagonal walls for ground agents.
                int sideA = Index(c.row, nc);
                int sideB = Index(nr, c.col);
                if (!IsWalkable(sideA, profile) || !IsWalkable(sideB, profile)) continue;
            }
            result.push_back(next);
        }
    }
    return result;
}

double GridMap::BaseMoveCost(int from, int to) const {
    GridCoord a = Coord(from);
    GridCoord b = Coord(to);
    int dr = std::abs(a.row - b.row);
    int dc = std::abs(a.col - b.col);
    return (dr == 1 && dc == 1) ? std::sqrt(2.0) : 1.0;
}

double GridMap::TerrainCost(int index) const {
    if (index < 0 || index >= Count()) return 1000000.0;
    switch (cells_[static_cast<size_t>(index)].terrain) {
        case TerrainType::Road: return 0.0;       // handled by a lower move multiplier
        case TerrainType::Forest: return 0.75;    // extra resistance
        case TerrainType::Mountain: return 1.45;  // rough ground penalty, independent from height
        case TerrainType::Water: return 1000000.0;
        case TerrainType::Plain:
        default: return 0.0;
    }
}

double GridMap::StepCost(int from, int to, double terrainWeight, double heightWeight) const {
    return StepCost(from, to, terrainWeight, heightWeight, MovementProfile::Pedestrian);
}

double GridMap::StepCost(int from, int to, double terrainWeight, double heightWeight, MovementProfile profile) const {
    if (!IsWalkable(from, profile) || !IsWalkable(to, profile)) return 1000000.0;

    double base = BaseMoveCost(from, to);
    double moveMultiplier = 1.0;
    double slopeMultiplier = 1.0;
    double terrainPenalty = TerrainCost(to);

    const TerrainType terrain = cells_[static_cast<size_t>(to)].terrain;

    if (profile == MovementProfile::Drone) {
        // A drone almost ignores ground terrain. Height is not climbing effort here;
        // it is only visual terrain elevation.
        return base * 0.85;
    }

    switch (profile) {
        case MovementProfile::Car:
            switch (terrain) {
                case TerrainType::Road:
                    moveMultiplier = 0.38;
                    slopeMultiplier = 0.25;
                    terrainPenalty = 0.0;
                    break;
                case TerrainType::Plain:
                    moveMultiplier = 1.80;
                    slopeMultiplier = 2.25;
                    terrainPenalty = 0.85;
                    break;
                case TerrainType::Forest:
                    moveMultiplier = 7.50;
                    slopeMultiplier = 3.50;
                    terrainPenalty = 6.0;
                    break;
                case TerrainType::Mountain:
                    moveMultiplier = 9.50;
                    slopeMultiplier = 5.50;
                    terrainPenalty = 8.0;
                    break;
                case TerrainType::Water:
                    return 1000000.0;
            }
            break;
        case MovementProfile::Offroad:
            switch (terrain) {
                case TerrainType::Road:
                    moveMultiplier = 0.70;
                    slopeMultiplier = 0.45;
                    terrainPenalty = 0.0;
                    break;
                case TerrainType::Forest:
                    moveMultiplier = 1.02;
                    slopeMultiplier = 0.90;
                    terrainPenalty = 0.25;
                    break;
                case TerrainType::Mountain:
                    moveMultiplier = 1.18;
                    slopeMultiplier = 1.20;
                    terrainPenalty = 0.55;
                    break;
                case TerrainType::Water:
                    return 1000000.0;
                case TerrainType::Plain:
                default:
                    moveMultiplier = 0.95;
                    break;
            }
            break;
        case MovementProfile::Pedestrian:
        default:
            switch (terrain) {
                case TerrainType::Road:
                    // Roads are better infrastructure, not lower altitude.
                    moveMultiplier = 0.62;
                    slopeMultiplier = 0.35;
                    terrainPenalty = 0.0;
                    break;
                case TerrainType::Forest:
                    moveMultiplier = 1.18;
                    slopeMultiplier = 1.05;
                    terrainPenalty = 0.75;
                    break;
                case TerrainType::Mountain:
                    moveMultiplier = 1.32;
                    slopeMultiplier = 1.85;
                    terrainPenalty = 1.45;
                    break;
                case TerrainType::Water:
                    return 1000000.0;
                case TerrainType::Plain:
                default:
                    break;
            }
            break;
    }

    int h1 = cells_[static_cast<size_t>(from)].height;
    int h2 = cells_[static_cast<size_t>(to)].height;
    const double height = std::abs(h1 - h2) * heightWeight * slopeMultiplier;
    return std::max(0.05, base * moveMultiplier + terrainWeight * terrainPenalty + height);
}

int GridMap::PickRandomFreeCell(std::mt19937& rng) const {
    std::uniform_int_distribution<int> dist(0, Count() - 1);
    for (int attempt = 0; attempt < 10000; ++attempt) {
        int candidate = dist(rng);
        if (IsWalkable(candidate)) return candidate;
    }
    for (int i = 0; i < Count(); ++i) {
        if (IsWalkable(i)) return i;
    }
    return 0;
}

void GridMap::EnsureEndpointsWalkable() {
    if (start_ < 0 || start_ >= Count()) start_ = 0;
    if (goal_ < 0 || goal_ >= Count()) goal_ = Count() - 1;
    auto makeWalkable = [&](int index) {
        cells_[static_cast<size_t>(index)].type = CellType::Empty;
        if (cells_[static_cast<size_t>(index)].terrain == TerrainType::Water) {
            cells_[static_cast<size_t>(index)].terrain = TerrainType::Plain;
        }
    };
    makeWalkable(start_);
    makeWalkable(goal_);
    if (start_ == goal_) {
        goal_ = std::clamp(Index(rows_ / 2, cols_ * 4 / 5), 0, Count() - 1);
        makeWalkable(goal_);
    }
}

} // namespace pathlab
